add pre-commit eslint and twig

diff --git a/templates/hooks/pre-commit-twig b/templates/hooks/pre-commit-twig
--- a/templates/hooks/pre-commit-twig
+++ b/templates/hooks/pre-commit-twig
@@ -11,14 +11,14 @@ then
 fi
 
 # Construct the phpcs command.
-command=$(echo "make -s phpcs files=\"${files}\"")
+command=$(echo "make -s twig-fix files=\"${files}\"")
 echo "$command"
 
 # Run the command on our docker container and capture the results
-make -s phpcs files="${files}" >> results_phpcs.txt
+make -s twig-fix files="${files}" >> results_twig.txt
 
-results=$(cat results_phpcs.txt)
-$(rm results_phpcs.txt)
+results=$(cat results_twig.txt)
+$(rm results_twig.txt)
 
 # Block the commit from going through if needed
 foundErrors=$(grep -o "begin diff" <<< ${results})
@@ -28,12 +28,7 @@ if [ "$foundErrors" != '' ]
 then
     echo "${results}" >&2
 
-    command=$(echo "make -s phpcs-fix options=\"--quiet\" files=\"${files}\"")
-    echo "$command"
-    
-    make -s phpcs-fix options="--quiet" files="${files}"
-     
-    echo "You had some phpcs errors, don't forget to add these fixes to git before committing again!" >&2
+    echo "You had some twig errors, don't forget to add these fixes to git before committing again!" >&2
 
     # Exit so you can stage the files and commit again
     returnCode=1
